spring.application.name=rating-service

spring.config.import=optional:classpath:application-secrets.properties

spring.neo4j.uri=${NEO4J_URI}
spring.neo4j.authentication.username=${NEO4J_USERNAME}
spring.neo4j.authentication.password=${NEO4J_PASSWORD}

spring.data.neo4j.database=${NEO4J_DATABASE}

jwt.secret=${JWT_SECRET}

movie.service.url=${MOVIE_SERVICE_URL}

server.port=${SERVER_PORT}